# Configuration for go-test-coverage tool
# https://github.com/vladopajic/go-test-coverage
profile: coverage/combined.out
threshold:
  # File coverage threshold (0-100)
  file: 70
  # Package coverage threshold (0-100)
  package: 80
  # Total coverage threshold (0-100)
  total: 75

exclude:
  # Exclude certain paths from coverage requirements
  paths:
    - ^example_tests/.*$
    - ^cmd/flakeguard/testscripts/.*$

# Badge generation (optional)
badge:
  filename: coverage.svg
